import { elementPickerPlugin } from './element_picker'
import pathUtils from 'path'
import { sveltePlugin } from './svelte'

export type BuildMode = 'ssr_worker' | 'standalone' | 'hydrate'

const entryFileForMode = (mode: BuildMode) => {
	if (mode === 'hydrate') return 'hydration_client.ts'
	if (mode === 'standalone') return 'standalone_client.ts'
	if (mode === 'ssr_worker') return 'ssr_worker.ts'

	throw new Error('invalid build mode')
}

export type BuildParams = {
	/** The path to this repo. */
	sdkPath: string

	/**
	 * The build mode to apply. Here is a rundown of each:
	 * - `standalone` results in a browser bundle that _renders UI_ based on state alongside any generic html template. Recommended for
	 *   SPAs or native applications.
	 * - `ssr_worker` results in a web worker that _emits HTML_ given state. It is expected that a `hydrate` build is used alongside this
	 *   generated html in the browser. Recommended for web applications.
	 * - `hydrate` results in a browser bundle that _hydrates ssr html and renders UI_ based on state. Expects to run alongside the html
	 *   generated by an `ssr` build. Recommended for web applications. */
	mode: BuildMode

	/** If true, CSS will be emitted in the `css` property of result. Otherwise, it will be ignored and `css` will be `null` */
	emitCss?: boolean

	/**
	 * Not implemented yet. Ideally, will embed fragments into the bundle. If false, which is default, fragments are not embedded,
	 * causing them to be loaded on-demand, drastically reducing bundle size.
	 *
	 * Fragments are large and complex modules of code that have limited runtime-only value (eg. maps, popovers, etc.) */
	embedFragments?: boolean
}

export async function build(params: BuildParams) {
	let combinedCss = ''

	const result = await Bun.build({
		target: params.mode === 'ssr_worker' ? 'bun' : 'browser',
		entrypoints: [`./main/${entryFileForMode(params.mode)}`],
		plugins: [
			await elementPickerPlugin(params.sdkPath, null),
			sveltePlugin({ onCss: params.emitCss ? css => (combinedCss += css) : undefined }),
		],
	})

	if (!result.success) throw new Error('build failed')
	if (!result.outputs[0]) throw new Error('invalid build output')

	return { code: await result.outputs[0].text(), css: params.emitCss ? combinedCss : null }
}

export type BuildAndWriteAllParams = {
	sdkPath: string
	outDir: string
}

export async function buildAndWriteAll(params: BuildAndWriteAllParams) {
	const [hydrationClientResult, standaloneClientResult, ssrWorkerResult] = await Promise.all([
		build({
			sdkPath: params.sdkPath,
			mode: 'hydrate',
			emitCss: true,
		}),
		build({
			sdkPath: params.sdkPath,
			mode: 'standalone',
		}),
		build({
			sdkPath: params.sdkPath,
			mode: 'ssr_worker',
		}),
	])

	if (!hydrationClientResult.css) throw new Error('expected css to be emitted')

	await Promise.all([
		Bun.write(pathUtils.join(params.outDir, 'hydration_client.js'), hydrationClientResult.code),
		Bun.write(pathUtils.join(params.outDir, 'standalone_client.js'), standaloneClientResult.code),
		Bun.write(pathUtils.join(params.outDir, 'ssr_worker.js'), ssrWorkerResult.code),
		Bun.write(pathUtils.join(params.outDir, 'combined.css'), hydrationClientResult.css),
	])
}
