[package]
name = "objection"
version = "0.1.0"
edition = "2021"

[lib]
path = "mod.rs"

[dependencies]
async_fn_traits = "0.1"
bincode = "1"
hex = "0.4"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
